# Generated by Django 4.2.7 on 2026-07-15 13:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('prescriptions', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_amount', models.BigIntegerField(default=0, verbose_name='مبلغ قبل از تخفیف')),
                ('amount', models.BigIntegerField(verbose_name='مبلغ نهایی پرداختی (تومان)')),
                ('discount_percentage', models.IntegerField(default=0, verbose_name='درصد تخفیف اعمال\u200cشده')),
                ('discount_source', models.CharField(blank=True, help_text='loyalty=باشگاه مشتریان / campaign=کمپین همگانی', max_length=50, verbose_name='منبع تخفیف')),
                ('is_cosmetic', models.BooleanField(default=False, verbose_name='اقلام آرایشی-بهداشتی')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='توضیحات')),
                ('purchase_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ خرید')),
                ('prescription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchases', to='prescriptions.prescription', verbose_name='نسخه')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'خرید',
                'verbose_name_plural': 'خریدها',
                'ordering': ['-purchase_date'],
            },
        ),
        migrations.CreateModel(
            name='GlobalDiscount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='نام کمپین')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('percentage', models.IntegerField(verbose_name='درصد تخفیف')),
                ('category', models.CharField(choices=[('cosmetic', 'اقلام آرایشی-بهداشتی'), ('all', 'همه اقلام')], default='cosmetic', max_length=20, verbose_name='دسته\u200cبندی')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('expires_at', models.DateTimeField(verbose_name='تاریخ انقضا')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_campaigns', to=settings.AUTH_USER_MODEL, verbose_name='ایجادکننده')),
            ],
            options={
                'verbose_name': 'کمپین تخفیف',
                'verbose_name_plural': 'کمپین\u200cهای تخفیف',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_type', models.CharField(choices=[('cosmetic', 'اقلام آرایشی-بهداشتی')], max_length=20, verbose_name='نوع تخفیف')),
                ('percentage', models.IntegerField(default=10, verbose_name='درصد تخفیف')),
                ('is_used', models.BooleanField(default=False, verbose_name='استفاده شده')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ استفاده')),
                ('expires_at', models.DateTimeField(verbose_name='تاریخ انقضا')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discounts', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'تخفیف وفاداری',
                'verbose_name_plural': 'تخفیف\u200cهای وفاداری',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CampaignUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('used_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ استفاده')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='customer_club.globaldiscount', verbose_name='کمپین')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_usages', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'استفاده از کمپین',
                'verbose_name_plural': 'استفاده\u200cهای کمپین',
                'unique_together': {('user', 'campaign')},
            },
        ),
    ]
