# Generated by Django 4.2.7 on 2026-05-25 07:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customer_club', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='discount',
            options={'ordering': ['-created_at'], 'verbose_name': 'تخفیف وفاداری', 'verbose_name_plural': 'تخفیف\u200cهای وفاداری'},
        ),
        migrations.AddField(
            model_name='purchase',
            name='discount_percentage',
            field=models.IntegerField(default=0, verbose_name='درصد تخفیف اعمال\u200cشده'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='discount_source',
            field=models.CharField(blank=True, help_text='loyalty=باشگاه مشتریان / campaign=کمپین همگانی', max_length=50, verbose_name='منبع تخفیف'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='is_cosmetic',
            field=models.BooleanField(default=False, verbose_name='اقلام آرایشی-بهداشتی'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='original_amount',
            field=models.BigIntegerField(default=0, verbose_name='مبلغ قبل از تخفیف'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='amount',
            field=models.BigIntegerField(verbose_name='مبلغ نهایی پرداختی (تومان)'),
        ),
        migrations.CreateModel(
            name='GlobalDiscount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='نام کمپین')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('percentage', models.IntegerField(verbose_name='درصد تخفیف')),
                ('category', models.CharField(choices=[('cosmetic', 'اقلام آرایشی-بهداشتی'), ('all', 'همه اقلام')], default='cosmetic', max_length=20, verbose_name='دسته\u200cبندی')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('expires_at', models.DateTimeField(verbose_name='تاریخ انقضا')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_campaigns', to=settings.AUTH_USER_MODEL, verbose_name='ایجادکننده')),
            ],
            options={
                'verbose_name': 'کمپین تخفیف',
                'verbose_name_plural': 'کمپین\u200cهای تخفیف',
                'ordering': ['-created_at'],
            },
        ),
    ]
