# Generated by Django 4.2.7 on 2026-05-25 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_club', '0002_alter_discount_options_purchase_discount_percentage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='used_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاریخ استفاده'),
        ),
    ]
