# Generated by Django 4.2.7 on 2026-05-26 09:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customer_club', '0003_discount_used_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('used_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ استفاده')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='customer_club.globaldiscount', verbose_name='کمپین')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_usages', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'استفاده از کمپین',
                'verbose_name_plural': 'استفاده\u200cهای کمپین',
                'unique_together': {('user', 'campaign')},
            },
        ),
    ]
