# Generated by Django 4.2.7 on 2026-07-15 13:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_code', models.CharField(max_length=50, verbose_name='کد رهگیری')),
                ('national_id', models.CharField(max_length=10, verbose_name='کد ملی')),
                ('insurance_type', models.CharField(choices=[('tamin', 'بیمه تأمین اجتماعی'), ('salamat', 'بیمه سلامت ایرانیان'), ('artesh', 'بیمه نیروهای مسلح'), ('iran', 'بیمه تکمیلی — ایران'), ('asia', 'بیمه تکمیلی — آسیا'), ('alborz', 'بیمه تکمیلی — البرز'), ('dana', 'بیمه تکمیلی — دانا'), ('day', 'بیمه تکمیلی — دی'), ('pasargad', 'بیمه تکمیلی — پاسارگاد'), ('saman', 'بیمه تکمیلی — سامان'), ('parsian', 'بیمه تکمیلی — پارسیان'), ('moalem', 'بیمه تکمیلی — معلم'), ('razi', 'بیمه تکمیلی — رازی'), ('sina', 'بیمه تکمیلی — سینا'), ('kowsar', 'بیمه تکمیلی — کوثر'), ('mellat', 'بیمه تکمیلی — ملت'), ('novin', 'بیمه تکمیلی — نوین'), ('hekmat', 'بیمه تکمیلی — حکمت صبا'), ('omid', 'بیمه تکمیلی — امید'), ('karafarinb', 'بیمه تکمیلی — کارآفرین'), ('tosee', 'بیمه تکمیلی — توسعه'), ('atiye', 'بیمه تکمیلی — آتیه\u200cسازان حافظ'), ('sos', 'بیمه تکمیلی — کمک\u200cرسان (SOS)'), ('free', 'آزاد (بدون بیمه)')], default='free', max_length=20, verbose_name='نوع بیمه')),
                ('contract_status', models.CharField(choices=[('unknown', 'بررسی نشده'), ('contracted', 'داروخانه قرارداد دارد'), ('no_contract', 'داروخانه قرارداد ندارد')], default='unknown', max_length=20, verbose_name='وضعیت قرارداد')),
                ('status', models.CharField(choices=[('pending', 'در حال بررسی'), ('items_entered', 'اقلام وارد شده'), ('ready', 'آماده تحویل'), ('partial', 'موجودی ناقص'), ('delivered', 'تحویل داده شده')], default='pending', max_length=20, verbose_name='وضعیت')),
                ('admin_notes', models.TextField(blank=True, verbose_name='توضیحات ادمین')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'نسخه',
                'verbose_name_plural': 'نسخه\u200cها',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PrescriptionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drug_name', models.CharField(max_length=200, verbose_name='نام دارو')),
                ('quantity', models.CharField(max_length=100, verbose_name='مقدار / تعداد')),
                ('dosage', models.CharField(blank=True, max_length=100, verbose_name='دوز / نحوه مصرف')),
                ('is_available', models.BooleanField(default=True, verbose_name='موجود است')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='prescriptions.prescription', verbose_name='نسخه')),
            ],
            options={
                'verbose_name': 'قلم نسخه',
                'verbose_name_plural': 'اقلام نسخه',
                'ordering': ['id'],
            },
        ),
    ]
