# Generated by Django 4.2.7 on 2026-07-14 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescriptions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='contract_status',
            field=models.CharField(choices=[('unknown', 'بررسی نشده'), ('contracted', 'داروخانه قرارداد دارد'), ('no_contract', 'داروخانه قرارداد ندارد')], default='unknown', max_length=20, verbose_name='وضعیت قرارداد'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='insurance_type',
            field=models.CharField(choices=[('tamin', 'بیمه تأمین اجتماعی'), ('salamat', 'بیمه سلامت ایرانیان'), ('artesh', 'بیمه نیروهای مسلح'), ('iran', 'بیمه تکمیلی — ایران'), ('asia', 'بیمه تکمیلی — آسیا'), ('alborz', 'بیمه تکمیلی — البرز'), ('dana', 'بیمه تکمیلی — دانا'), ('day', 'بیمه تکمیلی — دی'), ('pasargad', 'بیمه تکمیلی — پاسارگاد'), ('saman', 'بیمه تکمیلی — سامان'), ('parsian', 'بیمه تکمیلی — پارسیان'), ('moalem', 'بیمه تکمیلی — معلم'), ('razi', 'بیمه تکمیلی — رازی'), ('sina', 'بیمه تکمیلی — سینا'), ('kowsar', 'بیمه تکمیلی — کوثر'), ('mellat', 'بیمه تکمیلی — ملت'), ('novin', 'بیمه تکمیلی — نوین'), ('hekmat', 'بیمه تکمیلی — حکمت صبا'), ('omid', 'بیمه تکمیلی — امید'), ('karafarinb', 'بیمه تکمیلی — کارآفرین'), ('tosee', 'بیمه تکمیلی — توسعه'), ('atiye', 'بیمه تکمیلی — آتیه\u200cسازان حافظ'), ('sos', 'بیمه تکمیلی — کمک\u200cرسان (SOS)'), ('free', 'آزاد (بدون بیمه)')], default='free', max_length=20, verbose_name='نوع بیمه'),
        ),
    ]
