# Generated by Django 4.2.7 on 2026-05-25 07:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('prescription', 'نسخه'), ('discount', 'تخفیف'), ('broadcast', 'پیام همگانی'), ('general', 'عمومی')], default='general', max_length=20, verbose_name='نوع'),
        ),
        migrations.CreateModel(
            name='BroadcastMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('message', models.TextField(verbose_name='متن پیام')),
                ('discount_percentage', models.IntegerField(blank=True, null=True, verbose_name='درصد تخفیف همگانی (اختیاری)')),
                ('sent_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ارسال')),
                ('recipient_count', models.IntegerField(default=0, verbose_name='تعداد دریافت\u200cکنندگان')),
                ('sent_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_broadcasts', to=settings.AUTH_USER_MODEL, verbose_name='فرستنده')),
            ],
            options={
                'verbose_name': 'پیام همگانی',
                'verbose_name_plural': 'پیام\u200cهای همگانی',
                'ordering': ['-sent_at'],
            },
        ),
    ]
